#pragma once

const char * relayListTourney =
	":\r\n"
	":The following tournaments are currently in progress:\r\n"
	": \r\n"
	":20  Lienz Open 2013 - Round 4      Round Over\r\n"
	":21  Lienz Open 2013 - Last Round      Round Started\r\n";

const char * relayListTourney2 =
	":\r\n"
	":There are no tournaments in progress.\r\n";

const char * relayListTourney3 =
	":\r\n"
	":The following tournaments are currently in progress:\r\n"
	": \r\n"
	":14  Reykjavik Open 2013 - Round 6                           Round Started\r\n"
	":16  German Bundesliga - Round 9                             Round Started\r\n"
	":18  Romania Champs - Round 8                                Round Over\r\n"
	":20  4NCL - round 7                                          Open\r\n"
	":21  6th Karkonosze Group A                                  Round Started\r\n"
	":22  Central Serbia Championhips - Rd 8                      Round Started\r\n"
	":23  Cappelle La Grande 2013 - Round 1                       Open\r\n";

const char * relayListGames = 
	":\r\n"
	":There are 12 games in the Lienz Open 2013 - Round 4\r\n"
	": \r\n"
	":179 GMSedlak          FMMicheli         1-0     B07\r\n"
	":26  CSchwarhofer      GMJovanovic       0-1     C41\r\n"
	":560 IMDiermair        FMHartl           1-0     A11\r\n"
	":114 HaraldHicker      GMPopovic         1/2-1/2 E92\r\n"
	":182 FMSchnider        WolfgangHaessler  1/2-1/2 A21\r\n"
	":586 EckehardPoenisch  FMHeinig          1/2-1/2 B13\r\n"
	":224 IMBorsos          ReinholdJenul     1-0     B03\r\n"
	":478 JoKristianLoberg  JosefAger         0-1     A01\r\n"
	":600 SZoernpfenning    ManuelUnterreiner 1/2-1/2 A39\r\n"
	":269 MDiotallevi       JensPiotraschke   1/2-1/2 B13\r\n"
	":638 LukasPruell       RobertRieger      0-1     A00\r\n"
	":451 GMBuhmann         ColinACostello    1-0     A15\r\n"
	":\r\n";

const char * relayInfoShow =
	":RelayInfo(TD)\r\n"
	":Current Relay Schedule\r\n"
	":----------------------\r\n"
	":\r\n"
	":+------------+-----+-------+------+------------------------+\r\n"
	":|            |     | Srvr. | Rnd. | Tournament to be       |\r\n"
	":| Date       | Day | Time  | Num. | Relayed                |\r\n"
	":+------------+-----|-------|------|------------------------|\r\n"
	":| 2013-02-10 | Sun | 00:00 |    5 | Noteboom Trny Group A  |\r\n"
	":| 2013-02-10 | Sun | 00:30 |    2 | Lienz Open             |\r\n"
	":| 2013-02-10 | Sun | 05:00 |   LR | Noteboom Trny Group A  |\r\n"
	":| 2013-02-10 | Sun | 06:00 |    4 | Grenke Chess Classic   |\r\n"
	":| 2013-02-10 | Sun | 09:00 |    3 | Lienz Open             |\r\n"
	":|            |     |       |      |                        |\r\n"
	":| 2013-02-11 | Mon | 06:00 |    5 | Grenke Chess Classic   |\r\n"
	":| 2013-02-11 | Mon | 09:00 |    4 | Lienz Open             |\r\n"
	":|            |     |       |      |                        |\r\n"
	":| 2013-02-12 | Tue | 09:00 |    5 | Lienz Open             |\r\n"
	":|            |     |       |      |                        |\r\n"
	":| 2013-02-13 | Wed | 06:00 |    6 | Grenke Chess Classic   |\r\n"
	":| 2013-02-13 | Wed | 09:00 |    6 | Lienz Open             |\r\n"
	":|            |     |       |      |                        |\r\n"
	":| 2013-02-14 | Thu | 06:00 |    7 | Grenke Chess Classic   |\r\n"
	":| 2013-02-14 | Thu | 09:00 |    7 | Lienz Open             |\r\n"
	":|            |     |       |      |                        |\r\n"
	":| 2013-02-15 | Fri | 05:00 |    8 | Lienz Open             |\r\n"
	":| 2013-02-15 | Fri | 06:00 |    8 | Grenke Chess Classic   |\r\n"
	":|            |     |       |      |                        |\r\n"
	":| 2013-02-16 | Sat | 00:00 |   LR | Lienz Open             |\r\n"
	":| 2013-02-16 | Sat | 06:00 |    9 | Grenke Chess Classic   |\r\n"
	":|            |     |       |      |                        |\r\n"
	":| 2013-02-17 | Sun | 04:00 |   LR | Grenke Chess Classic   |\r\n"
	":|            |     |       |      |                        |\r\n"
	":+------------+-----+-------+------+------------------------+\r\n"
	": \r\n"
	":Notes:\r\n"
	":All times shown are server time.\r\n"
	":\"LR\" means \"Last Round.\"\r\n"
	":\"TB\" means \"Tie-Breaker\" which will only be played if needed.\r\n"
	":\"??\" means the value is unknown or the relay is still in doubt.\r\n"
	":\"N/A\" means \"Not Applicable\" which means it can be ignored.\r\n"
	":\r\n"
	":For more details about these tournaments, visit the FICS Relay web pages:\r\n"
	":http://www.freechess.org/Events/Relay/\r\n";

const char * relayInfoShow2 =
	":RelayInfo(TD)\r\n"
	":Current Relay Schedule\r\n"
	":----------------------\r\n"
	":\r\n"
	":+------------+-----+-------+------+------------------------+\r\n"
	":|            |     | Srvr. | Rnd. | Tournament to be       |\r\n"
	":| Date       | Day | Time  | Num. | Relayed                |\r\n"
	":+------------+-----|-------|------|------------------------|\r\n"
	":| 2013-02-22 | Fri | 05:00 |    7 | Romania Champ's Women  |\r\n"
	":| 2013-02-22 | Fri | 05:00 |    9 | Romania Champ's Men    |\r\n"
	":| 2013-02-22 | Fri | 06:00 |    7 | Karkonosze Open Group A|\r\n"
	":| 2013-02-22 | Fri | 07:00 |    7 | Cen.Serbia Champ's Men |\r\n"
	":| 2013-02-22 | Fri | 08:30 |    5 | Reykjavik Open         |\r\n"
	":|            |     |       |      |                        |\r\n"
	":| 2013-02-23 | Sat | 05:00 |    6 | Reykjavik Open         |\r\n"
	":| 2013-02-23 | Sat | 05:00 |    8 | Romania Champ's Women  |\r\n"
	":| 2013-02-23 | Sat | 05:00 |    9 | German Bundesliga      |\r\n"
	":| 2013-02-23 | Sat | 05:00 |   10 | Romania Champ's Men    |\r\n"
	":| 2013-02-23 | Sat | 06:00 |    5 | 4NCL                   |\r\n"
	":| 2013-02-23 | Sat | 06:00 |    8 | Karkonosze Open Group A|\r\n"
	":| 2013-02-23 | Sat | 07:00 |    1 | Cappelle La Grande     |\r\n"
	":| 2013-02-23 | Sat | 07:00 |    8 | Cen.Serbia Champ's Men |\r\n"
	":| 2013-02-23 | Sat | 23:30 |   LR | Romania Champ's Women  |\r\n"
	":| 2013-02-23 | Sat | 23:30 |   LR | Romania Champ's Men    |\r\n"
	":|            |     |       |      |                        |\r\n"
	":| 2013-02-24 | Sun | 00:00 |   LR | Karkonosze Open Group A|\r\n"
	":| 2013-02-24 | Sun | 00:00 |   LR | Cen.Serbia Champ's Men |\r\n"
	":| 2013-02-24 | Sun | 01:00 |   10 | German Bundesliga      |\r\n"
	":| 2013-02-24 | Sun | 03:00 |    6 | 4NCL                   |\r\n"
	":| 2013-02-24 | Sun | 05:00 |    2 | Cappelle La Grande     |\r\n"
	":| 2013-02-24 | Sun | 05:00 |    7 | Reykjavik Open         |\r\n"
	":|            |     |       |      |                        |\r\n"
	":| 2013-02-25 | Mon | 00:00 |    3 | Cappelle La Grande     |\r\n"
	":| 2013-02-25 | Mon | 07:00 |    4 | Cappelle La Grande     |\r\n"
	":| 2013-02-25 | Mon | 08:30 |    8 | Reykjavik Open         |\r\n"
	":|            |     |       |      |                        |\r\n"
	":| 2013-02-26 | Tue | 05:00 |    5 | Cappelle La Grande     |\r\n"
	":| 2013-02-26 | Tue | 08:30 |    9 | Reykjavik Open         |\r\n"
	":|            |     |       |      |                        |\r\n"
	":| 2013-02-27 | Wed | 04:00 |   LR | Reykjavik Open         |\r\n"
	":| 2013-02-27 | Wed | 05:00 |    6 | Cappelle La Grande     |\r\n"
	":|            |     |       |      |                        |\r\n"
	":| 2013-02-28 | Thu | 05:00 |    7 | Cappelle La Grande     |\r\n"
	":|            |     |       |      |                        |\r\n"
	":| 2013-03-01 | Fri | 05:00 |    8 | Cappelle La Grande     |\r\n"
	":|            |     |       |      |                        |\r\n"
	":| 2013-03-02 | Sat | 01:00 |   LR | Cappelle La Grande     |\r\n"
	":|            |     |       |      |                        |\r\n"
	":+------------+-----+-------+------+------------------------+\r\n"
	": \r\n"
	":Notes:\r\n"
	":All times shown are server time.\r\n"
	":\"LR\" means \"Last Round.\"\r\n"
	":\"TB\" means \"Tie-Breaker\" which will only be played if needed.\r\n"
	":\"??\" means the value is unknown or the relay is still in doubt.\r\n"
	":\"N/A\" means \"Not Applicable\" which means it can be ignored.\r\n"
	":\r\n"
	":For more details about these tournaments, visit the FICS Relay web pages:\r\n"
	":http://www.freechess.org/Events/Relay/\r\n";
